name: Main Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 src/

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2"

      - name: Lint Terraform code
        run: |
          terraform fmt --recursive --check

  apply:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          sudo apt-get install -y terraform

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan & Apply
        run: |
          cd terraform
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan